"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-06-06. It consists of a test
suite for recognizers that identify gc_1247 and a number of related classes. Specifically, **if**
the required recognizers are available, the test suite should contain:

    - a positive test for gc_1247;
    - a positive test for each recognizable ancestor of gc_1247;
    - a negative test for each class excluded by gc_1247;
    - and a negative test for each descendant of each class excluded by gc_1247.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/gc_1247 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
import graph_recognition.recognizers_n_3
import graph_recognition.profitable_hereditary_n_2
import graph_recognition.recognizers_exponential
import graph_recognition.recognizers_n_6
import graph_recognition.fisc_based_recognizers
import graph_recognition.profitable_hereditary_n_3
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_4
import graph_recognition.profitable_hereditary_n_4
import graph_recognition.recognizers_n_5
import graph_recognition.profitable_hereditary_n
import graph_recognition.recognizers_n_7
from graph_recognition import profitable_hereditary_n_4, recognizers_n_10
from readwrite import process_graphs


class Test_gc_1247_and_related(unittest.TestCase):
    """A generic test case for class gc_1247 and all its ancestors that have not already been
    covered by other tests."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_gc_1247_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/K2-free=gc_1247"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")

    # Generated test for base class gc_1247:
    def test_gc_1247(self) -> None:
        """Tests positive instances for class gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_k2_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    # Generated tests for ancestors of base class gc_1247 not yet covered by other tests:
    def test_gc_425(self) -> None:
        """Tests positive instances for class gc_425. gc_425 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_diamond_co_diamond_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1309(self) -> None:
        """Tests positive instances for class gc_1309. gc_1309 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1309(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_170(self) -> None:
        """Tests positive instances for class gc_170. gc_170 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_2k2_p4_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2761(self) -> None:
        """Tests positive instances for class AUTO_2761. AUTO_2761 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_s3_co_cnplus4_co_claw_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2113(self) -> None:
        """Tests positive instances for class AUTO_2113. AUTO_2113 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2113(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1930(self) -> None:
        """Tests positive instances for class AUTO_1930. AUTO_1930 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1930(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_827(self) -> None:
        """Tests positive instances for class gc_827. gc_827 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_probe_bipartite_chain(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2135(self) -> None:
        """Tests positive instances for class AUTO_2135. AUTO_2135 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_auto_2135(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1940(self) -> None:
        """Tests positive instances for class AUTO_1940. AUTO_1940 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                profitable_hereditary_n_4.is_auto_1940(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2765(self) -> None:
        """Tests positive instances for class AUTO_2765. AUTO_2765 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_co_cnplus4_h_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_417(self) -> None:
        """Tests positive instances for class gc_417. gc_417 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_split(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2074(self) -> None:
        """Tests positive instances for class AUTO_2074. AUTO_2074 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2074(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_443(self) -> None:
        """Tests positive instances for class gc_443. gc_443 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1301(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2990(self) -> None:
        """Tests positive instances for class AUTO_2990. AUTO_2990 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2990(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2108(self) -> None:
        """Tests positive instances for class AUTO_2108. AUTO_2108 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_k333_co_cnplus4_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1521(self) -> None:
        """Tests positive instances for class AUTO_1521. AUTO_1521 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1521(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1536(self) -> None:
        """Tests positive instances for class AUTO_1536. AUTO_1536 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1536(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_245(self) -> None:
        """Tests positive instances for class gc_245. gc_245 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_245(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_744(self) -> None:
        """Tests positive instances for class AUTO_744. AUTO_744 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_744(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1526(self) -> None:
        """Tests positive instances for class AUTO_1526. AUTO_1526 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1526(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2095(self) -> None:
        """Tests positive instances for class AUTO_2095. AUTO_2095 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_s3_co_cnplus4_co_t2_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2760(self) -> None:
        """Tests positive instances for class AUTO_2760. AUTO_2760 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_co_chordal_and_co_claw_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_174(self) -> None:
        """Tests positive instances for class gc_174. gc_174 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_4.is_dilworth_4(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1244(self) -> None:
        """Tests positive instances for class gc_1244. gc_1244 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_gc_1244(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1518(self) -> None:
        """Tests positive instances for class AUTO_1518. AUTO_1518 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1518(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_37(self) -> None:
        """Tests positive instances for class gc_37. gc_37 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_38(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_929(self) -> None:
        """Tests positive instances for class gc_929. gc_929 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_929(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1312(self) -> None:
        """Tests positive instances for class gc_1312. gc_1312 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1312(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2767(self) -> None:
        """Tests positive instances for class AUTO_2767. AUTO_2767 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_co_cnplus4_bull_house_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2147(self) -> None:
        """Tests positive instances for class AUTO_2147. AUTO_2147 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_auto_2147(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1077(self) -> None:
        """Tests positive instances for class gc_1077. gc_1077 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_1074(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_687(self) -> None:
        """Tests positive instances for class gc_687. gc_687 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_2_bounded_bipartite(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_802(self) -> None:
        """Tests positive instances for class gc_802. gc_802 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_806(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2120(self) -> None:
        """Tests positive instances for class AUTO_2120. AUTO_2120 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2120(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_539(self) -> None:
        """Tests positive instances for class gc_539. gc_539 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_bipartite_and_bithreshold(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1249(self) -> None:
        """Tests positive instances for class gc_1249. gc_1249 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_3.is_co_p3_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1519(self) -> None:
        """Tests positive instances for class AUTO_1519. AUTO_1519 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1519(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1238(self) -> None:
        """Tests positive instances for class gc_1238. gc_1238 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1765(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_3700(self) -> None:
        """Tests positive instances for class AUTO_3700. AUTO_3700 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_3700(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1307(self) -> None:
        """Tests positive instances for class gc_1307. gc_1307 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1307(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_331(self) -> None:
        """Tests positive instances for class gc_331. gc_331 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_threshold(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_3856(self) -> None:
        """Tests positive instances for class AUTO_3856. AUTO_3856 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                recognizers_n_10.is_co_b_perfect_and_chordal(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2148(self) -> None:
        """Tests positive instances for class AUTO_2148. AUTO_2148 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_co_circular_arc_and_diamond_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_627(self) -> None:
        """Tests positive instances for class gc_627. gc_627 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_627(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2140(self) -> None:
        """Tests positive instances for class AUTO_2140. AUTO_2140 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2140(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1467(self) -> None:
        """Tests positive instances for class AUTO_1467. AUTO_1467 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_auto_1467(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2785(self) -> None:
        """Tests positive instances for class AUTO_2785. AUTO_2785 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_s3_co_cnplus4_net_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2105(self) -> None:
        """Tests positive instances for class AUTO_2105. AUTO_2105 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_co_cnplus4_bull_co_dart_co_gem_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_159(self) -> None:
        """Tests positive instances for class gc_159. gc_159 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_co_interval(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2768(self) -> None:
        """Tests positive instances for class AUTO_2768. AUTO_2768 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_co_cnplus4_co_claw_co_gem_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1313(self) -> None:
        """Tests positive instances for class gc_1313. gc_1313 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1313(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_685(self) -> None:
        """Tests positive instances for class gc_685. gc_685 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_1_bounded_bipartite(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_970(self) -> None:
        """Tests positive instances for class gc_970. gc_970 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_co_line(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_688(self) -> None:
        """Tests positive instances for class gc_688. gc_688 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_688(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_744(self) -> None:
        """Tests positive instances for class gc_744. gc_744 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_co_line_graph_of_bipartite_graph(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_578(self) -> None:
        """Tests positive instances for class gc_578. gc_578 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_gc_578(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2773(self) -> None:
        """Tests positive instances for class AUTO_2773. AUTO_2773 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_k33_k33_plus_e2_p3_cnplus4_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1512(self) -> None:
        """Tests positive instances for class AUTO_1512. AUTO_1512 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1512(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1267(self) -> None:
        """Tests positive instances for class gc_1267. gc_1267 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_probe_co_bipartite(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2442(self) -> None:
        """Tests positive instances for class AUTO_2442. AUTO_2442 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_co_proper_helly_circular_arc(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2093(self) -> None:
        """Tests positive instances for class AUTO_2093. AUTO_2093 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_co_cnplus4_co_x_59_co_longhorn_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2133(self) -> None:
        """Tests positive instances for class AUTO_2133. AUTO_2133 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_co_cnplus4_co_claw_co_gem_house_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2107(self) -> None:
        """Tests positive instances for class AUTO_2107. AUTO_2107 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_auto_2107(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_558(self) -> None:
        """Tests positive instances for class gc_558. gc_558 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_166(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_316(self) -> None:
        """Tests positive instances for class gc_316. gc_316 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_strict_2_threshold(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1939(self) -> None:
        """Tests positive instances for class AUTO_1939. AUTO_1939 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                profitable_hereditary_n_4.is_p4_co_diamond_co_paw_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1460(self) -> None:
        """Tests positive instances for class AUTO_1460. AUTO_1460 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1460(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1735(self) -> None:
        """Tests positive instances for class AUTO_1735. AUTO_1735 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1735(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1304(self) -> None:
        """Tests positive instances for class gc_1304. gc_1304 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_gc_1304(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2094(self) -> None:
        """Tests positive instances for class AUTO_2094. AUTO_2094 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2094(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_971(self) -> None:
        """Tests positive instances for class gc_971. gc_971 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_balanced_and_co_line(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_173(self) -> None:
        """Tests positive instances for class gc_173. gc_173 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_dilworth_3(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1037(self) -> None:
        """Tests positive instances for class gc_1037. gc_1037 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_1037(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2119(self) -> None:
        """Tests positive instances for class AUTO_2119. AUTO_2119 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_auto_2119(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1246(self) -> None:
        """Tests positive instances for class gc_1246. gc_1246 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_gc_1246(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2779(self) -> None:
        """Tests positive instances for class AUTO_2779. AUTO_2779 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_s3_cnplus4_co_claw_net_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_990(self) -> None:
        """Tests positive instances for class gc_990. gc_990 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_gc_1(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1761(self) -> None:
        """Tests positive instances for class AUTO_1761. AUTO_1761 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_auto_1761(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_3683(self) -> None:
        """Tests positive instances for class AUTO_3683. AUTO_3683 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_3683(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2276(self) -> None:
        """Tests positive instances for class AUTO_2276. AUTO_2276 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_cnplus3_u_k1_co_diamond_co_paw_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1474(self) -> None:
        """Tests positive instances for class AUTO_1474. AUTO_1474 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1474(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_803(self) -> None:
        """Tests positive instances for class gc_803. gc_803 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2139(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1562(self) -> None:
        """Tests positive instances for class AUTO_1562. AUTO_1562 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_3k2_co_paw_odd_anti_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1300(self) -> None:
        """Tests positive instances for class gc_1300. gc_1300 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_p3_triangle_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2071(self) -> None:
        """Tests positive instances for class AUTO_2071. AUTO_2071 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2071(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1305(self) -> None:
        """Tests positive instances for class gc_1305. gc_1305 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_3.is_gc_1305(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1821(self) -> None:
        """Tests positive instances for class AUTO_1821. AUTO_1821 is an ancestor of gc_1247."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1821(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")
