"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-05-05. It consists of a test
suite for recognizers that identify gc_342 and a number of related classes. Specifically, **if** the
required recognizers are available, the test suite should contain:

    - a positive test for gc_342;
    - a positive test for each recognizable ancestor of gc_342;
    - a negative test for each class excluded by gc_342;
    - and a negative test for each descendant of each class excluded by gc_342.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/gc_342 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
import networkx.algorithms.components.biconnected
import graph_recognition.recognizers_n_3
import graph_recognition.profitable_hereditary_n_3
import graph_recognition.recognizers_n_9
import graph_recognition.recognizers_n
import graph_recognition.profitable_hereditary_n_4
import graph_recognition.profitable_hereditary_n_2
import graph_recognition.recognizers_n_5
import graph_recognition.profitable_hereditary_n
import graph_recognition.recognizers_exponential
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_4
import graph_recognition.recognizers_n_6
import graph_recognition.fisc_based_recognizers
from readwrite import process_graphs


class Test_gc_342_and_related(unittest.TestCase):
    """A generic test case for class gc_342 and all its ancestors that have not already been covered
    by other tests."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_gc_342_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/trees=gc_342"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")

    # Generated test for base class gc_342:
    def test_gc_342(self) -> None:
        """Tests positive instances for class gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_tree(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    # Generated tests for ancestors of base class gc_342 not yet covered by other tests:
    def test_gc_416(self) -> None:
        """Tests positive instances for class gc_416. gc_416 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_bipartite(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_912(self) -> None:
        """Tests positive instances for class gc_912. gc_912 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_4.is_c4_triangle_free_and_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_122(self) -> None:
        """Tests positive instances for class gc_122. gc_122 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_perfect_elimination_bipartite(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1728(self) -> None:
        """Tests positive instances for class AUTO_1728. AUTO_1728 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1728(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1339(self) -> None:
        """Tests positive instances for class gc_1339. gc_1339 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_3.is_planar_and_triangle_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_656(self) -> None:
        """Tests positive instances for class gc_656. gc_656 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_4.is_cnplus4_k4_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_985(self) -> None:
        """Tests positive instances for class gc_985. gc_985 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_chordal_and_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1181(self) -> None:
        """Tests positive instances for class gc_1181. gc_1181 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_2.is_apex(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_593(self) -> None:
        """Tests positive instances for class gc_593. gc_593 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_domino_hole_odd_cycle_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_651(self) -> None:
        """Tests positive instances for class gc_651. gc_651 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_cnplus4_bull_dart_gem_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1500(self) -> None:
        """Tests positive instances for class AUTO_1500. AUTO_1500 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_auto_1500(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1022(self) -> None:
        """Tests positive instances for class gc_1022. gc_1022 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_1022(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_917(self) -> None:
        """Tests positive instances for class gc_917. gc_917 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_917(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_663(self) -> None:
        """Tests positive instances for class gc_663. gc_663 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_9.is3_k_3_cnplus4_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_126(self) -> None:
        """Tests positive instances for class gc_126. gc_126 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_comparability_and_weakly_chordal(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1367(self) -> None:
        """Tests positive instances for class gc_1367. gc_1367 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_k4_free_and_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_903(self) -> None:
        """Tests positive instances for class gc_903. gc_903 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_outerplanar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_911(self) -> None:
        """Tests positive instances for class gc_911. gc_911 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_gc_911(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1277(self) -> None:
        """Tests positive instances for class gc_1277. gc_1277 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_hole_free_and_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_284(self) -> None:
        """Tests positive instances for class gc_284. gc_284 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_perfect_and_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_261(self) -> None:
        """Tests positive instances for class gc_261. gc_261 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_median(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_35(self) -> None:
        """Tests positive instances for class gc_35. gc_35 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_s3_net_free_and_chordal(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_43(self) -> None:
        """Tests positive instances for class gc_43. gc_43 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1190(self) -> None:
        """Tests positive instances for class gc_1190. gc_1190 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_xc_13_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_94(self) -> None:
        """Tests positive instances for class gc_94. gc_94 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_block(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_918(self) -> None:
        """Tests positive instances for class gc_918. gc_918 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_c4_c5_k4_diamond_free_and_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_759(self) -> None:
        """Tests positive instances for class AUTO_759. AUTO_759 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_c4_c6_free_and_bipartite(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1069(self) -> None:
        """Tests positive instances for class gc_1069. gc_1069 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_bipartite_and_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1225(self) -> None:
        """Tests positive instances for class gc_1225. gc_1225 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_3.is_girth_at_least_9(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1024(self) -> None:
        """Tests positive instances for class gc_1024. gc_1024 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_1024(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_50(self) -> None:
        """Tests positive instances for class gc_50. gc_50 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_modular(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_108(self) -> None:
        """Tests positive instances for class gc_108. gc_108 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_cactus(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1169(self) -> None:
        """Tests positive instances for class gc_1169. gc_1169 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_3.is_median_and_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_117(self) -> None:
        """Tests positive instances for class gc_117. gc_117 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_hole_odd_cycle_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1231(self) -> None:
        """Tests positive instances for class gc_1231. gc_1231 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_domino_gem_hole_house_net_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1497(self) -> None:
        """Tests positive instances for class AUTO_1497. AUTO_1497 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1497(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1020(self) -> None:
        """Tests positive instances for class gc_1020. gc_1020 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_cnplus3_u_k1_diamond_paw_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_772(self) -> None:
        """Tests positive instances for class AUTO_772. AUTO_772 is an ancestor of gc_342."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_chordal_and_comparability(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1362(self) -> None:
        """Tests negative instances for class gc_1362."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.recognizers_n.is_2_edge_connected(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_771(self) -> None:
        """Tests negative instances for class gc_771. gc_771 is a descendant of excluded class gc_1362."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                networkx.algorithms.components.biconnected.is_biconnected(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1235(self) -> None:
        """Tests negative instances for class gc_1235. gc_1235 is a descendant of excluded class gc_1362."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.recognizers_n_6.is_2_connected_and_p6_claw_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_773(self) -> None:
        """Tests negative instances for class gc_773. gc_773 is a descendant of excluded class gc_1362."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.recognizers_n_6.is_2_connected_and_gc_772(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1183(self) -> None:
        """Tests negative instances for class gc_1183. gc_1183 is a descendant of excluded class gc_1362."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_2_connected_cubic_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1099(self) -> None:
        """Tests negative instances for class gc_1099."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.recognizers_n.is_regular_with_k_at_least_3(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1100(self) -> None:
        """Tests negative instances for class gc_1100."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_cubic(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1334(self) -> None:
        """Tests negative instances for class gc_1334. gc_1334 is a descendant of excluded class gc_1100."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_bipartite_cubic_planar(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1102(self) -> None:
        """Tests negative instances for class gc_1102. gc_1102 is a descendant of excluded class gc_1100."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_cubic_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1101(self) -> None:
        """Tests negative instances for class gc_1101."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_4_regular(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1103(self) -> None:
        """Tests negative instances for class gc_1103. gc_1103 is a descendant of excluded class gc_1101."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_4_regular_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1104(self) -> None:
        """Tests negative instances for class gc_1104."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_5_regular(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1106(self) -> None:
        """Tests negative instances for class gc_1106. gc_1106 is a descendant of excluded class gc_1104."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.profitable_hereditary_n.is_5_regular_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1105(self) -> None:
        """Tests negative instances for class gc_1105."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertFalse(
                graph_recognition.recognizers_n.is_regular_with_k_at_least_6(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")
