"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-09-24. It consists of a test
suite for recognizers that identify gc_283 and a number of related classes. Specifically, **if** the
required recognizers are available, the test suite should contain:

    - a positive test for gc_283;
    - a positive test for each recognizable ancestor of gc_283;
    - a negative test for each class excluded by gc_283;
    - and a negative test for each descendant of each class excluded by gc_283.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/gc_283 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
import graph_recognition.recognizers_exponential
import graph_recognition.profitable_hereditary_n
import graph_recognition.recognizers_n_2
import graph_recognition.fisc_based_recognizers_n_5
from readwrite import process_graphs


class Test_gc_283_and_related(unittest.TestCase):
    """Tests class gc_283 and related classes using the dataset identified by perfect-and-
    planar=gc_283."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_gc_283_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/perfect-and-planar=gc_283"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")
        # Generated test for base class gc_283:

    def test_gc_283(self) -> None:
        """Tests positive instances for class gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_perfect_and_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    # Generated positive tests for ancestors of the base class:

    def test_gc_356(self) -> None:
        """Tests positive instances for class gc_356. gc_356 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_odd_hole_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_274(self) -> None:
        """Tests positive instances for class gc_274. gc_274 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_perfect(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_490(self) -> None:
        """Tests positive instances for class gc_490. gc_490 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_5.is_c5_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_43(self) -> None:
        """Tests positive instances for class gc_43. gc_43 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_planar(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1789(self) -> None:
        """Tests positive instances for class AUTO_1789. AUTO_1789 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_c7_odd_anti_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1181(self) -> None:
        """Tests positive instances for class gc_1181. gc_1181 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_2.is_apex(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1258(self) -> None:
        """Tests positive instances for class gc_1258. gc_1258 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_coc7_paw_odd_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_623(self) -> None:
        """Tests positive instances for class gc_623. gc_623 is an ancestor of gc_283."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_odd_anti_hole_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")
