"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-05-07. It consists of a test
suite for recognizers that identify AUTO_2774 and a number of related classes. Specifically, **if**
the required recognizers are available, the test suite should contain:

    - a positive test for AUTO_2774;
    - a positive test for each recognizable ancestor of AUTO_2774;
    - a negative test for each class excluded by AUTO_2774;
    - and a negative test for each descendant of each class excluded by AUTO_2774.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/AUTO_2774 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
import graph_recognition.profitable_hereditary_n_5
import graph_recognition.profitable_hereditary_n
import graph_recognition.recognizers_n_7
import graph_recognition.recognizers_n_6
import graph_recognition.profitable_hereditary_n_2
import graph_recognition.recognizers_exponential
import graph_recognition.recognizers_n_8
import graph_recognition.fisc_based_recognizers
import graph_recognition.recognizers_n_5
import graph_recognition.profitable_hereditary_n_4
from readwrite import process_graphs


class Test_AUTO_2774_and_related(unittest.TestCase):
    """A generic test case for class AUTO_2774 and all its ancestors that have not already been
    covered by other tests."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_AUTO_2774_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/co-block=AUTO_2774"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")

    # Generated test for base class AUTO_2774:
    def test_AUTO_2774(self) -> None:
        """Tests positive instances for class AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_co_chordal_and_co_diamond_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    # Generated tests for ancestors of base class AUTO_2774 not yet covered by other tests:
    def test_AUTO_1485(self) -> None:
        """Tests positive instances for class AUTO_1485. AUTO_1485 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1485(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1563(self) -> None:
        """Tests positive instances for class AUTO_1563. AUTO_1563 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1563(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1561(self) -> None:
        """Tests positive instances for class AUTO_1561. AUTO_1561 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_3k2_e_net_odd_anti_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2594(self) -> None:
        """Tests positive instances for class AUTO_2594. AUTO_2594 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_co_cnplus4_co_dart_co_gem_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2770(self) -> None:
        """Tests positive instances for class AUTO_2770. AUTO_2770 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_co_diamond_odd_anti_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2098(self) -> None:
        """Tests positive instances for class AUTO_2098. AUTO_2098 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_5.is_co_xc_10_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2207(self) -> None:
        """Tests positive instances for class AUTO_2207. AUTO_2207 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_co_x_37_co_diamond_even_anti_cycle_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2077(self) -> None:
        """Tests positive instances for class AUTO_2077. AUTO_2077 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_co_chordal(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2459(self) -> None:
        """Tests positive instances for class AUTO_2459. AUTO_2459 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_8.is_auto_2459(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2206(self) -> None:
        """Tests positive instances for class AUTO_2206. AUTO_2206 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_co_diamond_even_anti_cycle_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1822(self) -> None:
        """Tests positive instances for class AUTO_1822. AUTO_1822 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1822(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_542(self) -> None:
        """Tests positive instances for class gc_542. gc_542 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_542(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2118(self) -> None:
        """Tests positive instances for class AUTO_2118. AUTO_2118 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_even_anti_cycle_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2131(self) -> None:
        """Tests positive instances for class AUTO_2131. AUTO_2131 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_auto_2131(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2786(self) -> None:
        """Tests positive instances for class AUTO_2786. AUTO_2786 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_co_cnplus4_net_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1482(self) -> None:
        """Tests positive instances for class AUTO_1482. AUTO_1482 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_5.is_auto_1482(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2778(self) -> None:
        """Tests positive instances for class AUTO_2778. AUTO_2778 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_co_chordal_and_co_gem_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1636(self) -> None:
        """Tests positive instances for class AUTO_1636. AUTO_1636 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_1636(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1611(self) -> None:
        """Tests positive instances for class AUTO_1611. AUTO_1611 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_2k2_odd_anti_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_394(self) -> None:
        """Tests positive instances for class gc_394. gc_394 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_2k2_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2839(self) -> None:
        """Tests positive instances for class AUTO_2839. AUTO_2839 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_exponential.is_3k2_e_p2up4_net_odd_anti_hole_odd_hole_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_927(self) -> None:
        """Tests positive instances for class gc_927. gc_927 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_927(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2132(self) -> None:
        """Tests positive instances for class AUTO_2132. AUTO_2132 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_7.is_auto_2132(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2188(self) -> None:
        """Tests positive instances for class AUTO_2188. AUTO_2188 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_auto_2188(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_1506(self) -> None:
        """Tests positive instances for class AUTO_1506. AUTO_1506 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_4.is_auto_1506(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2595(self) -> None:
        """Tests positive instances for class AUTO_2595. AUTO_2595 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_6.is_k3_union3_k1_co_cnplus4_co_dart_co_gem_free(
                    graph
                ),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1275(self) -> None:
        """Tests positive instances for class gc_1275. gc_1275 is an ancestor of AUTO_2774."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers.is_gc_1275(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")
