"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-03-12. It consists of a test
suite for recognizers that identify gc_56 and a number of related classes. Specifically, **if** the
required recognizers are available, the test suite should contain:

    - a positive test for gc_56;
    - a positive test for each recognizable ancestor of gc_56;
    - a negative test for each class excluded by gc_56;
    - and a negative test for each descendant of each class excluded by gc_56.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/gc_56 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
from readwrite import process_graphs


class Test_gc_56_and_related(unittest.TestCase):
    """A generic test case for class gc_56 and all its ancestors that have not already been covered
    by other tests."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_gc_56_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/perfect=gc_56"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")

    # No recognizer was found for class gc_56 or any equivalent class, so no test could be generated for
    # that specific class
    # Generated tests for ancestors of base class gc_56:
