"""Anthony Labarre © 2026

This file was automatically generated by generate_tests.py on 2026-09-24. It consists of a test
suite for recognizers that identify gc_249 and a number of related classes. Specifically, **if** the
required recognizers are available, the test suite should contain:

    - a positive test for gc_249;
    - a positive test for each recognizable ancestor of gc_249;
    - a negative test for each class excluded by gc_249;
    - and a negative test for each descendant of each class excluded by gc_249.

Depending on which recognizers have been implemented and which representative of set of equivalent
class has been chosen, some class ids may have been substituted with equivalent ids according to
ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either in order to avoid
duplicating tests or because the needed recognizers were missing.

Check https://www.graphclasses.org/classes/gc_249 for more information.
"""

# Imports -----------------------------------------------------------------------------------------
import os
import sys
import unittest
import networkx
import graph_recognition.fisc_based_recognizers_n_7
import graph_recognition.fisc_based_recognizers_n_4
import graph_recognition.fisc_based_recognizers_n_11
import graph_recognition.profitable_hereditary_n
import graph_recognition.profitable_hereditary_n_2
import graph_recognition.recognizers_n_4
import graph_recognition.fisc_based_recognizers_n_9
import graph_recognition.fisc_based_recognizers_n_5
import graph_recognition.fisc_based_recognizers_n_8
import graph_recognition.fisc_based_recognizers_n_6
from readwrite import process_graphs


class Test_gc_249_and_related(unittest.TestCase):
    """Tests class gc_249 and related classes using the dataset identified by line=gc_249."""

    @classmethod
    def setUpClass(self) -> None:
        """Stores positive and negative instances to test."""
        super(Test_gc_249_and_related, self).setUpClass()
        self.positive = []
        basedir = "./tests/test_data/line=gc_249"
        print(
            self.__qualname__.join("[]"),
            "initializing positive instances from",
            basedir,
            "...",
            end=" ",
        )
        sys.stdout.flush()

        # the slice below restricts tests to 5 files in order to keep the running times reasonable
        for dataset in sorted(
            os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size
        )[:5]:
            try:
                self.positive.extend(
                    graph for graph in process_graphs(os.path.join(basedir, dataset))
                )
            except ValueError as err:
                print(
                    "[Warning] unsupported extension for",
                    os.path.basename(dataset),
                    ", skipping",
                )
        print("done.")
        # Generated test for base class gc_249:

    def test_gc_249(self) -> None:
        """Tests positive instances for class gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n.is_line(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    # Generated positive tests for ancestors of the base class:

    def test_gc_814(self) -> None:
        """Tests positive instances for class gc_814. gc_814 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_5.is_p_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_362(self) -> None:
        """Tests positive instances for class gc_362. gc_362 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_5.is_k23_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_819(self) -> None:
        """Tests positive instances for class gc_819. gc_819 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_8.is_gc_819(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_811(self) -> None:
        """Tests positive instances for class gc_811. gc_811 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_9.is_gc_811(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_550(self) -> None:
        """Tests positive instances for class gc_550. gc_550 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_11.is_gc_550(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_329(self) -> None:
        """Tests positive instances for class AUTO_329. AUTO_329 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_co_p7_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1276(self) -> None:
        """Tests positive instances for class gc_1276. gc_1276 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_gc_1276(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_590(self) -> None:
        """Tests positive instances for class gc_590. gc_590 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_gc_590(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_879(self) -> None:
        """Tests positive instances for class gc_879. gc_879 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.profitable_hereditary_n_2.is_quasi_line(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_818(self) -> None:
        """Tests positive instances for class gc_818. gc_818 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_gc_818(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_816(self) -> None:
        """Tests positive instances for class gc_816. gc_816 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_e_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_735(self) -> None:
        """Tests positive instances for class gc_735. gc_735 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_k2_u_claw_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_592(self) -> None:
        """Tests positive instances for class gc_592. gc_592 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_domino_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_388(self) -> None:
        """Tests positive instances for class gc_388. gc_388 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_5.is_k14_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_62(self) -> None:
        """Tests positive instances for class gc_62. gc_62 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_4.is_claw_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_756(self) -> None:
        """Tests positive instances for class gc_756. gc_756 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_gc_756(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_1145(self) -> None:
        """Tests positive instances for class gc_1145. gc_1145 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.recognizers_n_4.is_almost_claw_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_391(self) -> None:
        """Tests positive instances for class gc_391. gc_391 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_5.is_fork_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_224(self) -> None:
        """Tests positive instances for class AUTO_224. AUTO_224 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_co_2p3_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2110(self) -> None:
        """Tests positive instances for class AUTO_2110. AUTO_2110 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_auto_2110(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_202(self) -> None:
        """Tests positive instances for class AUTO_202. AUTO_202 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_auto_202(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_588(self) -> None:
        """Tests positive instances for class gc_588. gc_588 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_8.is_gc_588(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_41(self) -> None:
        """Tests positive instances for class AUTO_41. AUTO_41 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_co_p6_free(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_AUTO_2123(self) -> None:
        """Tests positive instances for class AUTO_2123. AUTO_2123 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_6.is_auto_2123(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")

    def test_gc_757(self) -> None:
        """Tests positive instances for class gc_757. gc_757 is an ancestor of gc_249."""
        print(
            self._testMethodName.join("[]"),
            "testing",
            len(self.positive),
            "graphs",
            end=" ",
        )
        sys.stdout.flush()

        # looping over enumerate so we can print failed instances
        for num, graph in enumerate(self.positive):
            self.assertTrue(
                graph_recognition.fisc_based_recognizers_n_7.is_gc_757(graph),
                "failed on graph number "
                + str(num)
                + " / "
                + str(len(self.positive))
                + " with node set "
                + str(graph.nodes)
                + " and edge set "
                + str(graph.edges),
            )

        print("done.")
