"""Anthony Labarre © 2024

This file was automatically generated by generate_tests.py on 2024-07-13. It
consists of a test suite for recognizers that identify gc_32 and / or all its
ancestors. Depending on which recognizers have been implemented, some class ids
may have been substituted with equivalent ids according to ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either
in order to avoid duplicating tests or because the needed recognizers were
missing.

Check https://www.graphclasses.org/classes/gc_32 for more information.

"""
# Imports ---------------------------------------------------------------------
import graph_recognition.fisc_based_recognizers
import graph_recognition.recognizers_n
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_4
import graph_recognition.recognizers_n_5
import networkx
import networkx.algorithms.chordal
import os
import sys
import unittest


class Test_gc_32_and_ancestors(unittest.TestCase):
    """A generic test case for class gc_32 and all its ancestors that have not
    already been covered by other tests."""
    @classmethod
    def setUpClass(self):
        """Stores positive and negative instances to test."""
        super(Test_gc_32_and_ancestors, self).setUpClass()
        self.positive = list()
        basedir = "tests/test_data/chordal=gc_32"
        print(self.__class__.__qualname__.join("[]"), "initialising positive instances from tests/test_data/chordal=gc_32...", end=" ")
        sys.stdout.flush()
        for dataset in sorted(os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size)[:5]:
            if dataset.endswith(".g6"):
                data = networkx.read_graph6(os.path.join(basedir, dataset))
            elif dataset.endswith(".s6"):
                data = networkx.read_sparse6(os.path.join(basedir, dataset))
            else:
                continue
            if not isinstance(data, list):
                data = [data]
            self.positive.extend(data)
        print("done.")

    def test_gc_32(self):
        """Tests positive instances for class gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(networkx.algorithms.chordal.is_chordal(g) for g in self.positive))
        print("done.")
    def test_AUTO_92(self):
        """Tests positive instances for class AUTO_92. AUTO_92 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_92(g) for g in self.positive))
        print("done.")
    def test_AUTO_1820(self):
        """Tests positive instances for class AUTO_1820. AUTO_1820 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1820(g) for g in self.positive))
        print("done.")
    def test_AUTO_202(self):
        """Tests positive instances for class AUTO_202. AUTO_202 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_202(g) for g in self.positive))
        print("done.")
    def test_AUTO_1473(self):
        """Tests positive instances for class AUTO_1473. AUTO_1473 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1473(g) for g in self.positive))
        print("done.")
    def test_gc_490(self):
        """Tests positive instances for class gc_490. gc_490 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_359(g) for g in self.positive))
        print("done.")
    def test_AUTO_94(self):
        """Tests positive instances for class AUTO_94. AUTO_94 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_anti_hole_free(g) for g in self.positive))
        print("done.")
    def test_gc_113(self):
        """Tests positive instances for class gc_113. gc_113 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hhp_free(g) for g in self.positive))
        print("done.")
    def test_gc_248(self):
        """Tests positive instances for class gc_248. gc_248 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n.is_chordal_or_co_chordal(g) for g in self.positive))
        print("done.")
    def test_AUTO_1470(self):
        """Tests positive instances for class AUTO_1470. AUTO_1470 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1470(g) for g in self.positive))
        print("done.")
    def test_gc_1254(self):
        """Tests positive instances for class gc_1254. gc_1254 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_2.is_locally_chordal(g) for g in self.positive))
        print("done.")
    def test_AUTO_41(self):
        """Tests positive instances for class AUTO_41. AUTO_41 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_41(g) for g in self.positive))
        print("done.")
    def test_AUTO_224(self):
        """Tests positive instances for class AUTO_224. AUTO_224 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_224(g) for g in self.positive))
        print("done.")
    def test_gc_592(self):
        """Tests positive instances for class gc_592. gc_592 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_592(g) for g in self.positive))
        print("done.")
    def test_gc_435(self):
        """Tests positive instances for class gc_435. gc_435 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_weakly_chordal(g) for g in self.positive))
        print("done.")
    def test_gc_609(self):
        """Tests positive instances for class gc_609. gc_609 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_pretty(g) for g in self.positive))
        print("done.")
    def test_AUTO_497(self):
        """Tests positive instances for class AUTO_497. AUTO_497 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_497(g) for g in self.positive))
        print("done.")
    def test_gc_1281(self):
        """Tests positive instances for class gc_1281. gc_1281 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1281(g) for g in self.positive))
        print("done.")
    def test_gc_437(self):
        """Tests positive instances for class gc_437. gc_437 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hole_free(g) for g in self.positive))
        print("done.")
    def test_gc_360(self):
        """Tests positive instances for class gc_360. gc_360 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_360(g) for g in self.positive))
        print("done.")
    def test_AUTO_2097(self):
        """Tests positive instances for class AUTO_2097. AUTO_2097 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2097(g) for g in self.positive))
        print("done.")
    def test_gc_436(self):
        """Tests positive instances for class gc_436. gc_436 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_436(g) for g in self.positive))
        print("done.")
    def test_gc_814(self):
        """Tests positive instances for class gc_814. gc_814 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_814(g) for g in self.positive))
        print("done.")
    def test_gc_400(self):
        """Tests positive instances for class gc_400. gc_400 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_5.is_k_23_p_hole_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2123(self):
        """Tests positive instances for class AUTO_2123. AUTO_2123 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2123(g) for g in self.positive))
        print("done.")
    def test_gc_590(self):
        """Tests positive instances for class gc_590. gc_590 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_590(g) for g in self.positive))
        print("done.")
    def test_AUTO_2096(self):
        """Tests positive instances for class AUTO_2096. AUTO_2096 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2096(g) for g in self.positive))
        print("done.")
    def test_AUTO_329(self):
        """Tests positive instances for class AUTO_329. AUTO_329 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_329(g) for g in self.positive))
        print("done.")
    def test_gc_351(self):
        """Tests positive instances for class gc_351. gc_351 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hhda_free(g) for g in self.positive))
        print("done.")
    def test_gc_228(self):
        """Tests positive instances for class gc_228. gc_228 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hh_free(g) for g in self.positive))
        print("done.")
    def test_gc_367(self):
        """Tests positive instances for class gc_367. gc_367 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_367(g) for g in self.positive))
        print("done.")
    def test_AUTO_2110(self):
        """Tests positive instances for class AUTO_2110. AUTO_2110 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2110(g) for g in self.positive))
        print("done.")
    def test_gc_230(self):
        """Tests positive instances for class gc_230. gc_230 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hhd_free(g) for g in self.positive))
        print("done.")
    def test_gc_433(self):
        """Tests positive instances for class gc_433. gc_433 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_433(g) for g in self.positive))
        print("done.")
    def test_AUTO_2104(self):
        """Tests positive instances for class AUTO_2104. AUTO_2104 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2104(g) for g in self.positive))
        print("done.")
    def test_gc_588(self):
        """Tests positive instances for class gc_588. gc_588 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_588(g) for g in self.positive))
        print("done.")
    def test_gc_362(self):
        """Tests positive instances for class gc_362. gc_362 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_362(g) for g in self.positive))
        print("done.")
    def test_gc_361(self):
        """Tests positive instances for class gc_361. gc_361 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_house_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_407(self):
        """Tests positive instances for class AUTO_407. AUTO_407 is an ancestor of gc_32."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_407(g) for g in self.positive))
        print("done.")