"""Anthony Labarre © 2024

This file was automatically generated by generate_tests.py on 2024-07-13. It
consists of a test suite for recognizers that identify gc_371 and / or all its
ancestors. Depending on which recognizers have been implemented, some class ids
may have been substituted with equivalent ids according to ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either
in order to avoid duplicating tests or because the needed recognizers were
missing.

Check https://www.graphclasses.org/classes/gc_371 for more information.

"""
# Imports ---------------------------------------------------------------------
import graph_recognition.fisc_based_recognizers
import graph_recognition.profitable_hereditary_n_3
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_3
import graph_recognition.recognizers_n_4
import graph_recognition.recognizers_n_5
import networkx
import os
import sys
import unittest


class Test_gc_371_and_ancestors(unittest.TestCase):
    """A generic test case for class gc_371 and all its ancestors that have not
    already been covered by other tests."""
    @classmethod
    def setUpClass(self):
        """Stores positive and negative instances to test."""
        super(Test_gc_371_and_ancestors, self).setUpClass()
        self.positive = list()
        basedir = "tests/test_data/triangle-free=gc_371"
        print(self.__class__.__qualname__.join("[]"), "initialising positive instances from tests/test_data/triangle-free=gc_371...", end=" ")
        sys.stdout.flush()
        for dataset in sorted(os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size)[:5]:
            if dataset.endswith(".g6"):
                data = networkx.read_graph6(os.path.join(basedir, dataset))
            elif dataset.endswith(".s6"):
                data = networkx.read_sparse6(os.path.join(basedir, dataset))
            else:
                continue
            if not isinstance(data, list):
                data = [data]
            self.positive.extend(data)
        print("done.")

    def test_gc_371(self):
        """Tests positive instances for class gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.profitable_hereditary_n_3.is_triangle_free(g) for g in self.positive))
        print("done.")
    def test_gc_455(self):
        """Tests positive instances for class gc_455. gc_455 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_455(g) for g in self.positive))
        print("done.")
    def test_AUTO_92(self):
        """Tests positive instances for class AUTO_92. AUTO_92 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_92(g) for g in self.positive))
        print("done.")
    def test_gc_1343(self):
        """Tests positive instances for class gc_1343. gc_1343 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1343(g) for g in self.positive))
        print("done.")
    def test_AUTO_1820(self):
        """Tests positive instances for class AUTO_1820. AUTO_1820 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1820(g) for g in self.positive))
        print("done.")
    def test_gc_441(self):
        """Tests positive instances for class gc_441. gc_441 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_441(g) for g in self.positive))
        print("done.")
    def test_AUTO_1442(self):
        """Tests positive instances for class AUTO_1442. AUTO_1442 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1442(g) for g in self.positive))
        print("done.")
    def test_gc_673(self):
        """Tests positive instances for class gc_673. gc_673 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_673(g) for g in self.positive))
        print("done.")
    def test_AUTO_2142(self):
        """Tests positive instances for class AUTO_2142. AUTO_2142 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2142(g) for g in self.positive))
        print("done.")
    def test_AUTO_1461(self):
        """Tests positive instances for class AUTO_1461. AUTO_1461 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1461(g) for g in self.positive))
        print("done.")
    def test_AUTO_202(self):
        """Tests positive instances for class AUTO_202. AUTO_202 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_202(g) for g in self.positive))
        print("done.")
    def test_gc_1263(self):
        """Tests positive instances for class gc_1263. gc_1263 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_locally_bipartite(g) for g in self.positive))
        print("done.")
    def test_AUTO_2398(self):
        """Tests positive instances for class AUTO_2398. AUTO_2398 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2398(g) for g in self.positive))
        print("done.")
    def test_AUTO_1511(self):
        """Tests positive instances for class AUTO_1511. AUTO_1511 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1511(g) for g in self.positive))
        print("done.")
    def test_AUTO_1514(self):
        """Tests positive instances for class AUTO_1514. AUTO_1514 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1514(g) for g in self.positive))
        print("done.")
    def test_AUTO_2124(self):
        """Tests positive instances for class AUTO_2124. AUTO_2124 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2124(g) for g in self.positive))
        print("done.")
    def test_gc_625(self):
        """Tests positive instances for class gc_625. gc_625 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_625(g) for g in self.positive))
        print("done.")
    def test_gc_376(self):
        """Tests positive instances for class gc_376. gc_376 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_376(g) for g in self.positive))
        print("done.")
    def test_gc_373(self):
        """Tests positive instances for class gc_373. gc_373 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_373(g) for g in self.positive))
        print("done.")
    def test_AUTO_3(self):
        """Tests positive instances for class AUTO_3. AUTO_3 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_3(g) for g in self.positive))
        print("done.")
    def test_gc_700(self):
        """Tests positive instances for class gc_700. gc_700 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_700(g) for g in self.positive))
        print("done.")
    def test_gc_386(self):
        """Tests positive instances for class gc_386. gc_386 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_386(g) for g in self.positive))
        print("done.")
    def test_gc_1254(self):
        """Tests positive instances for class gc_1254. gc_1254 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_2.is_locally_chordal(g) for g in self.positive))
        print("done.")
    def test_AUTO_2141(self):
        """Tests positive instances for class AUTO_2141. AUTO_2141 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2141(g) for g in self.positive))
        print("done.")
    def test_AUTO_1523(self):
        """Tests positive instances for class AUTO_1523. AUTO_1523 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1523(g) for g in self.positive))
        print("done.")
    def test_AUTO_41(self):
        """Tests positive instances for class AUTO_41. AUTO_41 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_41(g) for g in self.positive))
        print("done.")
    def test_AUTO_224(self):
        """Tests positive instances for class AUTO_224. AUTO_224 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_224(g) for g in self.positive))
        print("done.")
    def test_gc_574(self):
        """Tests positive instances for class gc_574. gc_574 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_574(g) for g in self.positive))
        print("done.")
    def test_gc_456(self):
        """Tests positive instances for class gc_456. gc_456 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_456(g) for g in self.positive))
        print("done.")
    def test_gc_609(self):
        """Tests positive instances for class gc_609. gc_609 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_pretty(g) for g in self.positive))
        print("done.")
    def test_AUTO_497(self):
        """Tests positive instances for class AUTO_497. AUTO_497 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_497(g) for g in self.positive))
        print("done.")
    def test_gc_54(self):
        """Tests positive instances for class gc_54. gc_54 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_5.is_clique_helly(g) for g in self.positive))
        print("done.")
    def test_AUTO_1767(self):
        """Tests positive instances for class AUTO_1767. AUTO_1767 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1767(g) for g in self.positive))
        print("done.")
    def test_gc_354(self):
        """Tests positive instances for class gc_354. gc_354 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_354(g) for g in self.positive))
        print("done.")
    def test_AUTO_1465(self):
        """Tests positive instances for class AUTO_1465. AUTO_1465 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1465(g) for g in self.positive))
        print("done.")
    def test_AUTO_2079(self):
        """Tests positive instances for class AUTO_2079. AUTO_2079 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2079(g) for g in self.positive))
        print("done.")
    def test_AUTO_2129(self):
        """Tests positive instances for class AUTO_2129. AUTO_2129 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_co_at_free_and_co_claw_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2097(self):
        """Tests positive instances for class AUTO_2097. AUTO_2097 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2097(g) for g in self.positive))
        print("done.")
    def test_AUTO_1464(self):
        """Tests positive instances for class AUTO_1464. AUTO_1464 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1464(g) for g in self.positive))
        print("done.")
    def test_gc_871(self):
        """Tests positive instances for class gc_871. gc_871 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_871(g) for g in self.positive))
        print("done.")
    def test_AUTO_1530(self):
        """Tests positive instances for class AUTO_1530. AUTO_1530 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1530(g) for g in self.positive))
        print("done.")
    def test_AUTO_1517(self):
        """Tests positive instances for class AUTO_1517. AUTO_1517 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1517(g) for g in self.positive))
        print("done.")
    def test_gc_1357(self):
        """Tests positive instances for class gc_1357. gc_1357 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1357(g) for g in self.positive))
        print("done.")
    def test_gc_1344(self):
        """Tests positive instances for class gc_1344. gc_1344 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1344(g) for g in self.positive))
        print("done.")
    def test_AUTO_2092(self):
        """Tests positive instances for class AUTO_2092. AUTO_2092 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2092(g) for g in self.positive))
        print("done.")
    def test_AUTO_1459(self):
        """Tests positive instances for class AUTO_1459. AUTO_1459 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1459(g) for g in self.positive))
        print("done.")
    def test_AUTO_2123(self):
        """Tests positive instances for class AUTO_2123. AUTO_2123 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2123(g) for g in self.positive))
        print("done.")
    def test_gc_1330(self):
        """Tests positive instances for class gc_1330. gc_1330 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1330(g) for g in self.positive))
        print("done.")
    def test_AUTO_1490(self):
        """Tests positive instances for class AUTO_1490. AUTO_1490 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1490(g) for g in self.positive))
        print("done.")
    def test_AUTO_1525(self):
        """Tests positive instances for class AUTO_1525. AUTO_1525 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1525(g) for g in self.positive))
        print("done.")
    def test_AUTO_2096(self):
        """Tests positive instances for class AUTO_2096. AUTO_2096 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2096(g) for g in self.positive))
        print("done.")
    def test_AUTO_329(self):
        """Tests positive instances for class AUTO_329. AUTO_329 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_329(g) for g in self.positive))
        print("done.")
    def test_AUTO_79(self):
        """Tests positive instances for class AUTO_79. AUTO_79 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_79(g) for g in self.positive))
        print("done.")
    def test_AUTO_1537(self):
        """Tests positive instances for class AUTO_1537. AUTO_1537 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1537(g) for g in self.positive))
        print("done.")
    def test_AUTO_2(self):
        """Tests positive instances for class AUTO_2. AUTO_2 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2(g) for g in self.positive))
        print("done.")
    def test_gc_372(self):
        """Tests positive instances for class gc_372. gc_372 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_372(g) for g in self.positive))
        print("done.")
    def test_AUTO_2127(self):
        """Tests positive instances for class AUTO_2127. AUTO_2127 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_co_at_free(g) for g in self.positive))
        print("done.")
    def test_gc_1359(self):
        """Tests positive instances for class gc_1359. gc_1359 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1359(g) for g in self.positive))
        print("done.")
    def test_AUTO_1476(self):
        """Tests positive instances for class AUTO_1476. AUTO_1476 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1476(g) for g in self.positive))
        print("done.")
    def test_gc_357(self):
        """Tests positive instances for class gc_357. gc_357 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.profitable_hereditary_n_3.is_gc_357(g) for g in self.positive))
        print("done.")
    def test_AUTO_1522(self):
        """Tests positive instances for class AUTO_1522. AUTO_1522 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1522(g) for g in self.positive))
        print("done.")
    def test_AUTO_2110(self):
        """Tests positive instances for class AUTO_2110. AUTO_2110 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2110(g) for g in self.positive))
        print("done.")
    def test_AUTO_1509(self):
        """Tests positive instances for class AUTO_1509. AUTO_1509 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1509(g) for g in self.positive))
        print("done.")
    def test_AUTO_2104(self):
        """Tests positive instances for class AUTO_2104. AUTO_2104 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2104(g) for g in self.positive))
        print("done.")
    def test_AUTO_1515(self):
        """Tests positive instances for class AUTO_1515. AUTO_1515 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1515(g) for g in self.positive))
        print("done.")
    def test_AUTO_1528(self):
        """Tests positive instances for class AUTO_1528. AUTO_1528 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1528(g) for g in self.positive))
        print("done.")
    def test_AUTO_1524(self):
        """Tests positive instances for class AUTO_1524. AUTO_1524 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1524(g) for g in self.positive))
        print("done.")
    def test_AUTO_1463(self):
        """Tests positive instances for class AUTO_1463. AUTO_1463 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1463(g) for g in self.positive))
        print("done.")
    def test_gc_361(self):
        """Tests positive instances for class gc_361. gc_361 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_house_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2125(self):
        """Tests positive instances for class AUTO_2125. AUTO_2125 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2125(g) for g in self.positive))
        print("done.")
    def test_AUTO_407(self):
        """Tests positive instances for class AUTO_407. AUTO_407 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_407(g) for g in self.positive))
        print("done.")
    def test_gc_748(self):
        """Tests positive instances for class gc_748. gc_748 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_748(g) for g in self.positive))
        print("done.")
    def test_AUTO_1520(self):
        """Tests positive instances for class AUTO_1520. AUTO_1520 is an ancestor of gc_371."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1520(g) for g in self.positive))
        print("done.")