"""Anthony Labarre © 2024

This file was automatically generated by generate_tests.py on 2024-07-13. It
consists of a test suite for recognizers that identify gc_486 and / or all its
ancestors. Depending on which recognizers have been implemented, some class ids
may have been substituted with equivalent ids according to ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either
in order to avoid duplicating tests or because the needed recognizers were
missing.

Check https://www.graphclasses.org/classes/gc_486 for more information.

"""
# Imports ---------------------------------------------------------------------
import graph_recognition.fisc_based_recognizers
import graph_recognition.profitable_hereditary_n_3
import graph_recognition.recognizers_n
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_3
import graph_recognition.recognizers_n_4
import graph_recognition.recognizers_n_5
import networkx
import networkx.algorithms.asteroidal
import os
import sys
import unittest


class Test_gc_486_and_ancestors(unittest.TestCase):
    """A generic test case for class gc_486 and all its ancestors that have not
    already been covered by other tests."""
    @classmethod
    def setUpClass(self):
        """Stores positive and negative instances to test."""
        super(Test_gc_486_and_ancestors, self).setUpClass()
        self.positive = list()
        basedir = "tests/test_data/cobipartite=gc_486"
        print(self.__class__.__qualname__.join("[]"), "initialising positive instances from tests/test_data/cobipartite=gc_486...", end=" ")
        sys.stdout.flush()
        for dataset in sorted(os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size)[:5]:
            if dataset.endswith(".g6"):
                data = networkx.read_graph6(os.path.join(basedir, dataset))
            elif dataset.endswith(".s6"):
                data = networkx.read_sparse6(os.path.join(basedir, dataset))
            else:
                continue
            if not isinstance(data, list):
                data = [data]
            self.positive.extend(data)
        print("done.")

    def test_gc_486(self):
        """Tests positive instances for class gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n.is_co_bipartite(g) for g in self.positive))
        print("done.")
    def test_AUTO_2583(self):
        """Tests positive instances for class AUTO_2583. AUTO_2583 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2583(g) for g in self.positive))
        print("done.")
    def test_gc_60(self):
        """Tests positive instances for class gc_60. gc_60 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_at_free_and_claw_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2467(self):
        """Tests positive instances for class AUTO_2467. AUTO_2467 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_co_locally_bipartite(g) for g in self.positive))
        print("done.")
    def test_gc_404(self):
        """Tests positive instances for class gc_404. gc_404 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_404(g) for g in self.positive))
        print("done.")
    def test_gc_1276(self):
        """Tests positive instances for class gc_1276. gc_1276 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1276(g) for g in self.positive))
        print("done.")
    def test_gc_61(self):
        """Tests positive instances for class gc_61. gc_61 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(networkx.algorithms.asteroidal.is_at_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2584(self):
        """Tests positive instances for class AUTO_2584. AUTO_2584 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2584(g) for g in self.positive))
        print("done.")
    def test_gc_819(self):
        """Tests positive instances for class gc_819. gc_819 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_819(g) for g in self.positive))
        print("done.")
    def test_gc_403(self):
        """Tests positive instances for class gc_403. gc_403 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_403(g) for g in self.positive))
        print("done.")
    def test_gc_355(self):
        """Tests positive instances for class gc_355. gc_355 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_355(g) for g in self.positive))
        print("done.")
    def test_gc_490(self):
        """Tests positive instances for class gc_490. gc_490 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_359(g) for g in self.positive))
        print("done.")
    def test_gc_572(self):
        """Tests positive instances for class gc_572. gc_572 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_572(g) for g in self.positive))
        print("done.")
    def test_gc_811(self):
        """Tests positive instances for class gc_811. gc_811 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_811(g) for g in self.positive))
        print("done.")
    def test_gc_376(self):
        """Tests positive instances for class gc_376. gc_376 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_376(g) for g in self.positive))
        print("done.")
    def test_gc_427(self):
        """Tests positive instances for class gc_427. gc_427 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_427(g) for g in self.positive))
        print("done.")
    def test_gc_373(self):
        """Tests positive instances for class gc_373. gc_373 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_373(g) for g in self.positive))
        print("done.")
    def test_AUTO_77(self):
        """Tests positive instances for class AUTO_77. AUTO_77 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_77(g) for g in self.positive))
        print("done.")
    def test_AUTO_1466(self):
        """Tests positive instances for class AUTO_1466. AUTO_1466 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1466(g) for g in self.positive))
        print("done.")
    def test_gc_386(self):
        """Tests positive instances for class gc_386. gc_386 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_386(g) for g in self.positive))
        print("done.")
    def test_gc_808(self):
        """Tests positive instances for class gc_808. gc_808 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_808(g) for g in self.positive))
        print("done.")
    def test_gc_1214(self):
        """Tests positive instances for class gc_1214. gc_1214 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1214(g) for g in self.positive))
        print("done.")
    def test_gc_428(self):
        """Tests positive instances for class gc_428. gc_428 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_428(g) for g in self.positive))
        print("done.")
    def test_gc_1361(self):
        """Tests positive instances for class gc_1361. gc_1361 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n.is_bipartite_or_co_bipartite_or_split(g) for g in self.positive))
        print("done.")
    def test_AUTO_2102(self):
        """Tests positive instances for class AUTO_2102. AUTO_2102 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2102(g) for g in self.positive))
        print("done.")
    def test_gc_816(self):
        """Tests positive instances for class gc_816. gc_816 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_816(g) for g in self.positive))
        print("done.")
    def test_gc_930(self):
        """Tests positive instances for class gc_930. gc_930 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_930(g) for g in self.positive))
        print("done.")
    def test_gc_439(self):
        """Tests positive instances for class gc_439. gc_439 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_439(g) for g in self.positive))
        print("done.")
    def test_gc_813(self):
        """Tests positive instances for class gc_813. gc_813 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_813(g) for g in self.positive))
        print("done.")
    def test_gc_647(self):
        """Tests positive instances for class gc_647. gc_647 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_647(g) for g in self.positive))
        print("done.")
    def test_gc_420(self):
        """Tests positive instances for class gc_420. gc_420 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_420(g) for g in self.positive))
        print("done.")
    def test_gc_408(self):
        """Tests positive instances for class gc_408. gc_408 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_408(g) for g in self.positive))
        print("done.")
    def test_gc_592(self):
        """Tests positive instances for class gc_592. gc_592 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_592(g) for g in self.positive))
        print("done.")
    def test_gc_674(self):
        """Tests positive instances for class gc_674. gc_674 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_674(g) for g in self.positive))
        print("done.")
    def test_gc_648(self):
        """Tests positive instances for class gc_648. gc_648 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_648(g) for g in self.positive))
        print("done.")
    def test_gc_138(self):
        """Tests positive instances for class gc_138. gc_138 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_137(g) for g in self.positive))
        print("done.")
    def test_AUTO_2117(self):
        """Tests positive instances for class AUTO_2117. AUTO_2117 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2117(g) for g in self.positive))
        print("done.")
    def test_gc_397(self):
        """Tests positive instances for class gc_397. gc_397 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_397(g) for g in self.positive))
        print("done.")
    def test_gc_928(self):
        """Tests positive instances for class gc_928. gc_928 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_928(g) for g in self.positive))
        print("done.")
    def test_gc_550(self):
        """Tests positive instances for class gc_550. gc_550 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_550(g) for g in self.positive))
        print("done.")
    def test_gc_432(self):
        """Tests positive instances for class gc_432. gc_432 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_432(g) for g in self.positive))
        print("done.")
    def test_gc_407(self):
        """Tests positive instances for class gc_407. gc_407 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_407(g) for g in self.positive))
        print("done.")
    def test_gc_735(self):
        """Tests positive instances for class gc_735. gc_735 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_735(g) for g in self.positive))
        print("done.")
    def test_gc_638(self):
        """Tests positive instances for class gc_638. gc_638 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_638(g) for g in self.positive))
        print("done.")
    def test_gc_388(self):
        """Tests positive instances for class gc_388. gc_388 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_388(g) for g in self.positive))
        print("done.")
    def test_gc_437(self):
        """Tests positive instances for class gc_437. gc_437 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hole_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2780(self):
        """Tests positive instances for class AUTO_2780. AUTO_2780 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_co_paw_odd_anti_hole_free(g) for g in self.positive))
        print("done.")
    def test_gc_683(self):
        """Tests positive instances for class gc_683. gc_683 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_683(g) for g in self.positive))
        print("done.")
    def test_gc_436(self):
        """Tests positive instances for class gc_436. gc_436 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_436(g) for g in self.positive))
        print("done.")
    def test_gc_756(self):
        """Tests positive instances for class gc_756. gc_756 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_756(g) for g in self.positive))
        print("done.")
    def test_AUTO_399(self):
        """Tests positive instances for class AUTO_399. AUTO_399 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.profitable_hereditary_n_3.is_AUTO_399(g) for g in self.positive))
        print("done.")
    def test_AUTO_1563(self):
        """Tests positive instances for class AUTO_1563. AUTO_1563 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1563(g) for g in self.positive))
        print("done.")
    def test_gc_814(self):
        """Tests positive instances for class gc_814. gc_814 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_814(g) for g in self.positive))
        print("done.")
    def test_gc_410(self):
        """Tests positive instances for class gc_410. gc_410 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_410(g) for g in self.positive))
        print("done.")
    def test_gc_1357(self):
        """Tests positive instances for class gc_1357. gc_1357 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1357(g) for g in self.positive))
        print("done.")
    def test_AUTO_1484(self):
        """Tests positive instances for class AUTO_1484. AUTO_1484 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1484(g) for g in self.positive))
        print("done.")
    def test_gc_915(self):
        """Tests positive instances for class gc_915. gc_915 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_915(g) for g in self.positive))
        print("done.")
    def test_gc_669(self):
        """Tests positive instances for class gc_669. gc_669 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_669(g) for g in self.positive))
        print("done.")
    def test_gc_400(self):
        """Tests positive instances for class gc_400. gc_400 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_5.is_k_23_p_hole_free(g) for g in self.positive))
        print("done.")
    def test_gc_1234(self):
        """Tests positive instances for class gc_1234. gc_1234 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1234(g) for g in self.positive))
        print("done.")
    def test_gc_431(self):
        """Tests positive instances for class gc_431. gc_431 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_431(g) for g in self.positive))
        print("done.")
    def test_gc_62(self):
        """Tests positive instances for class gc_62. gc_62 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_claw_free(g) for g in self.positive))
        print("done.")
    def test_gc_423(self):
        """Tests positive instances for class gc_423. gc_423 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_423(g) for g in self.positive))
        print("done.")
    def test_gc_590(self):
        """Tests positive instances for class gc_590. gc_590 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_590(g) for g in self.positive))
        print("done.")
    def test_gc_757(self):
        """Tests positive instances for class gc_757. gc_757 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_757(g) for g in self.positive))
        print("done.")
    def test_AUTO_2465(self):
        """Tests positive instances for class AUTO_2465. AUTO_2465 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_2.is_co_locally_chordal(g) for g in self.positive))
        print("done.")
    def test_gc_396(self):
        """Tests positive instances for class gc_396. gc_396 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_396(g) for g in self.positive))
        print("done.")
    def test_gc_931(self):
        """Tests positive instances for class gc_931. gc_931 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_931(g) for g in self.positive))
        print("done.")
    def test_gc_758(self):
        """Tests positive instances for class gc_758. gc_758 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_758(g) for g in self.positive))
        print("done.")
    def test_gc_391(self):
        """Tests positive instances for class gc_391. gc_391 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_391(g) for g in self.positive))
        print("done.")
    def test_gc_1267(self):
        """Tests positive instances for class gc_1267. gc_1267 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_probe_co_bipartite(g) for g in self.positive))
        print("done.")
    def test_gc_759(self):
        """Tests positive instances for class gc_759. gc_759 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_759(g) for g in self.positive))
        print("done.")
    def test_gc_737(self):
        """Tests positive instances for class gc_737. gc_737 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_737(g) for g in self.positive))
        print("done.")
    def test_gc_372(self):
        """Tests positive instances for class gc_372. gc_372 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_372(g) for g in self.positive))
        print("done.")
    def test_gc_1359(self):
        """Tests positive instances for class gc_1359. gc_1359 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1359(g) for g in self.positive))
        print("done.")
    def test_AUTO_2188(self):
        """Tests positive instances for class AUTO_2188. AUTO_2188 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2188(g) for g in self.positive))
        print("done.")
    def test_gc_1145(self):
        """Tests positive instances for class gc_1145. gc_1145 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_almost_claw_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_1892(self):
        """Tests positive instances for class AUTO_1892. AUTO_1892 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1892(g) for g in self.positive))
        print("done.")
    def test_AUTO_1453(self):
        """Tests positive instances for class AUTO_1453. AUTO_1453 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_1453(g) for g in self.positive))
        print("done.")
    def test_AUTO_198(self):
        """Tests positive instances for class AUTO_198. AUTO_198 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_2.is_quasi_line(g) for g in self.positive))
        print("done.")
    def test_gc_563(self):
        """Tests positive instances for class gc_563. gc_563 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_563(g) for g in self.positive))
        print("done.")
    def test_gc_588(self):
        """Tests positive instances for class gc_588. gc_588 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_588(g) for g in self.positive))
        print("done.")
    def test_gc_362(self):
        """Tests positive instances for class gc_362. gc_362 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_362(g) for g in self.positive))
        print("done.")
    def test_gc_818(self):
        """Tests positive instances for class gc_818. gc_818 is an ancestor of gc_486."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_818(g) for g in self.positive))
        print("done.")