"""Anthony Labarre © 2024

This file was automatically generated by generate_tests.py on 2024-07-13. It
consists of a test suite for recognizers that identify gc_23 and / or all its
ancestors. Depending on which recognizers have been implemented, some class ids
may have been substituted with equivalent ids according to ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either
in order to avoid duplicating tests or because the needed recognizers were
missing.

Check https://www.graphclasses.org/classes/gc_23 for more information.

"""
# Imports ---------------------------------------------------------------------
import graph_recognition.fisc_based_recognizers
import graph_recognition.recognizers_n_2
import graph_recognition.recognizers_n_3
import graph_recognition.recognizers_n_4
import networkx
import networkx.algorithms.asteroidal
import os
import sys
import unittest


class Test_gc_23_and_ancestors(unittest.TestCase):
    """A generic test case for class gc_23 and all its ancestors that have not
    already been covered by other tests."""
    @classmethod
    def setUpClass(self):
        """Stores positive and negative instances to test."""
        super(Test_gc_23_and_ancestors, self).setUpClass()
        self.positive = list()
        basedir = "tests/test_data/permutation=gc_23"
        print(self.__class__.__qualname__.join("[]"), "initialising positive instances from tests/test_data/permutation=gc_23...", end=" ")
        sys.stdout.flush()
        for dataset in sorted(os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size)[:5]:
            if dataset.endswith(".g6"):
                data = networkx.read_graph6(os.path.join(basedir, dataset))
            elif dataset.endswith(".s6"):
                data = networkx.read_sparse6(os.path.join(basedir, dataset))
            else:
                continue
            if not isinstance(data, list):
                data = [data]
            self.positive.extend(data)
        print("done.")

    def test_AUTO_92(self):
        """Tests positive instances for class AUTO_92. AUTO_92 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_92(g) for g in self.positive))
        print("done.")
    def test_gc_61(self):
        """Tests positive instances for class gc_61. gc_61 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(networkx.algorithms.asteroidal.is_at_free(g) for g in self.positive))
        print("done.")
    def test_gc_490(self):
        """Tests positive instances for class gc_490. gc_490 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_359(g) for g in self.positive))
        print("done.")
    def test_AUTO_94(self):
        """Tests positive instances for class AUTO_94. AUTO_94 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_anti_hole_free(g) for g in self.positive))
        print("done.")
    def test_gc_376(self):
        """Tests positive instances for class gc_376. gc_376 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_376(g) for g in self.positive))
        print("done.")
    def test_gc_373(self):
        """Tests positive instances for class gc_373. gc_373 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_373(g) for g in self.positive))
        print("done.")
    def test_gc_386(self):
        """Tests positive instances for class gc_386. gc_386 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_386(g) for g in self.positive))
        print("done.")
    def test_gc_435(self):
        """Tests positive instances for class gc_435. gc_435 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_weakly_chordal(g) for g in self.positive))
        print("done.")
    def test_gc_437(self):
        """Tests positive instances for class gc_437. gc_437 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_4.is_hole_free(g) for g in self.positive))
        print("done.")
    def test_AUTO_2097(self):
        """Tests positive instances for class AUTO_2097. AUTO_2097 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2097(g) for g in self.positive))
        print("done.")
    def test_gc_436(self):
        """Tests positive instances for class gc_436. gc_436 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_436(g) for g in self.positive))
        print("done.")
    def test_gc_1357(self):
        """Tests positive instances for class gc_1357. gc_1357 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_1357(g) for g in self.positive))
        print("done.")
    def test_AUTO_2096(self):
        """Tests positive instances for class AUTO_2096. AUTO_2096 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2096(g) for g in self.positive))
        print("done.")
    def test_gc_590(self):
        """Tests positive instances for class gc_590. gc_590 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_590(g) for g in self.positive))
        print("done.")
    def test_gc_767(self):
        """Tests positive instances for class gc_767. gc_767 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_2.is_comparability(g) for g in self.positive))
        print("done.")
    def test_AUTO_2134(self):
        """Tests positive instances for class AUTO_2134. AUTO_2134 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_AUTO_2134(g) for g in self.positive))
        print("done.")
    def test_AUTO_2127(self):
        """Tests positive instances for class AUTO_2127. AUTO_2127 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.is_co_at_free(g) for g in self.positive))
        print("done.")
    def test_gc_779(self):
        """Tests positive instances for class gc_779. gc_779 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_779(g) for g in self.positive))
        print("done.")
    def test_gc_433(self):
        """Tests positive instances for class gc_433. gc_433 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_433(g) for g in self.positive))
        print("done.")
    def test_gc_588(self):
        """Tests positive instances for class gc_588. gc_588 is an ancestor of gc_23."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.fisc_based_recognizers.is_gc_588(g) for g in self.positive))
        print("done.")