"""Anthony Labarre © 2024

This file was automatically generated by generate_tests.py on 2024-07-13. It
consists of a test suite for recognizers that identify gc_1148 and / or all its
ancestors. Depending on which recognizers have been implemented, some class ids
may have been substituted with equivalent ids according to ISGCI.

Some of the ancestors may have been purposefully omitted from this file, either
in order to avoid duplicating tests or because the needed recognizers were
missing.

Check https://www.graphclasses.org/classes/gc_1148 for more information.

"""
# Imports ---------------------------------------------------------------------
import graph_recognition.recognizers_n_3
import networkx
import networkx.algorithms.regular
import os
import sys
import unittest


class Test_gc_1148_and_ancestors(unittest.TestCase):
    """A generic test case for class gc_1148 and all its ancestors that have not
    already been covered by other tests."""
    @classmethod
    def setUpClass(self):
        """Stores positive and negative instances to test."""
        super(Test_gc_1148_and_ancestors, self).setUpClass()
        self.positive = list()
        basedir = "tests/test_data/distance-regular=gc_1148"
        print(self.__class__.__qualname__.join("[]"), "initialising positive instances from tests/test_data/distance-regular=gc_1148...", end=" ")
        sys.stdout.flush()
        for dataset in sorted(os.listdir(basedir), key=lambda x: os.stat(os.path.join(basedir, x)).st_size)[:5]:
            if dataset.endswith(".g6"):
                data = networkx.read_graph6(os.path.join(basedir, dataset))
            elif dataset.endswith(".s6"):
                data = networkx.read_sparse6(os.path.join(basedir, dataset))
            else:
                continue
            if not isinstance(data, list):
                data = [data]
            self.positive.extend(data)
        print("done.")

    def test_gc_1148(self):
        """Tests positive instances for class gc_1148."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(graph_recognition.recognizers_n_3.my_is_distance_regular(g) for g in self.positive))
        print("done.")
    def test_gc_1149(self):
        """Tests positive instances for class gc_1149. gc_1149 is an ancestor of gc_1148."""
        print(
            self._testMethodName.join("[]"), "testing", len(self.positive), "graphs", end=" "
        )
        sys.stdout.flush()
        self.assertTrue(all(networkx.algorithms.regular.is_regular(g) for g in self.positive))
        print("done.")